import { extractZugferdXmlFromPdf } from "./extract-zugferd-xml-from-pdf";

/**
 * pdfjs-dist ships ESM-only (no CommonJS build) — Jest's CommonJS-based module runtime can't
 * execute its real `.mjs` file (it contains genuine `import.meta` syntax, invalid outside a real
 * ES module loader), even though Node itself handles the dynamic `import()` in
 * extract-zugferd-xml-from-pdf.ts fine via its native "require(esm)" interop (see that file's own
 * doc comment). So this suite mocks pdfjs-dist's two methods this module actually calls
 * (`getAttachments`/`getAttachmentContent`) to exercise every branch of the extraction logic
 * under Jest.
 *
 * **The real, unmocked extraction was verified separately during development**, against an actual
 * ZUGFeRD hybrid PDF/A-3 generated by this codebase's own PdfService.renderZugferdInvoice() +
 * buildZugferdCiiXml() (the same functions InvoicesService.generateZugferdPdf() uses in
 * production) — confirmed byte-for-byte identical extracted XML, via a real `ts-node` run outside
 * Jest's module system. If pdfjs-dist's API shape ever changes, that manual check is what would
 * catch it, not this file — re-run it after any pdfjs-dist version bump.
 */

const mockGetDocument = jest.fn();
jest.mock(
  "pdfjs-dist/legacy/build/pdf.mjs",
  () => ({
    getDocument: (...args: unknown[]) => mockGetDocument(...args),
  }),
  { virtual: true },
);

describe("extractZugferdXmlFromPdf (pdfjs-dist mocked — see file header for the real, unmocked verification)", () => {
  beforeEach(() => {
    mockGetDocument.mockReset();
  });

  function mockLoadingTask(attachments: Map<string, unknown> | null, contentByName: Record<string, string> = {}) {
    const destroy = jest.fn().mockResolvedValue(undefined);
    const doc = {
      getAttachments: jest.fn().mockResolvedValue(attachments),
      getAttachmentContent: jest.fn((name: string) => Promise.resolve(contentByName[name] ? new TextEncoder().encode(contentByName[name]) : null)),
    };
    mockGetDocument.mockReturnValue({ promise: Promise.resolve(doc), destroy });
    return { doc, destroy };
  }

  it("extracts the content of the first .xml-named attachment", async () => {
    const xml = "<rsm:CrossIndustryInvoice>fake</rsm:CrossIndustryInvoice>";
    mockLoadingTask(new Map([["factur-x.xml", {}]]), { "factur-x.xml": xml });

    const result = await extractZugferdXmlFromPdf(Buffer.from("fake-pdf-bytes"));

    expect(result).toBe(xml);
  });

  it("ignores a non-XML attachment and returns null when no .xml attachment exists", async () => {
    mockLoadingTask(new Map([["logo.png", {}]]), {});

    const result = await extractZugferdXmlFromPdf(Buffer.from("fake-pdf-bytes"));

    expect(result).toBeNull();
  });

  it("returns null when the PDF has no attachments at all", async () => {
    mockLoadingTask(null);

    const result = await extractZugferdXmlFromPdf(Buffer.from("fake-pdf-bytes"));

    expect(result).toBeNull();
  });

  it("always destroys the loading task, even after a successful extraction", async () => {
    const { destroy } = mockLoadingTask(new Map([["factur-x.xml", {}]]), { "factur-x.xml": "<x/>" });

    await extractZugferdXmlFromPdf(Buffer.from("fake-pdf-bytes"));

    expect(destroy).toHaveBeenCalledTimes(1);
  });

  it("destroys the loading task even when getAttachments throws", async () => {
    const destroy = jest.fn().mockResolvedValue(undefined);
    const doc = { getAttachments: jest.fn().mockRejectedValue(new Error("corrupt PDF")) };
    mockGetDocument.mockReturnValue({ promise: Promise.resolve(doc), destroy });

    await expect(extractZugferdXmlFromPdf(Buffer.from("fake-pdf-bytes"))).rejects.toThrow("corrupt PDF");

    expect(destroy).toHaveBeenCalledTimes(1);
  });
});
