import { Controller, Get, Param } from "@nestjs/common";
import { Public } from "../common/decorators/public.decorator";
import { SubcontractorsService } from "./subcontractors.service";

/** Unauthenticated — reached only via the token embedded in the link generated by
 * SubcontractorsService.setPublicListed(). */
@Controller("public/subcontractor-profiles")
export class PublicSubcontractorsController {
  constructor(private readonly service: SubcontractorsService) {}

  @Public()
  @Get(":token")
  get(@Param("token") token: string) {
    return this.service.getPublicProfile(token);
  }
}
