-- AlterTable
ALTER TABLE "material_catalog_items" ADD COLUMN     "preferredSupplierId" TEXT,
ADD COLUMN     "reorderQuantity" DECIMAL(14,4);

-- AlterTable
ALTER TABLE "purchase_orders" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "stock_movements" ADD COLUMN     "toWarehouseId" TEXT;

-- CreateIndex
CREATE INDEX "material_catalog_items_preferredSupplierId_idx" ON "material_catalog_items"("preferredSupplierId");

-- CreateIndex
CREATE INDEX "stock_movements_toWarehouseId_idx" ON "stock_movements"("toWarehouseId");

-- AddForeignKey
ALTER TABLE "material_catalog_items" ADD CONSTRAINT "material_catalog_items_preferredSupplierId_fkey" FOREIGN KEY ("preferredSupplierId") REFERENCES "suppliers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_toWarehouseId_fkey" FOREIGN KEY ("toWarehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
