import { Logger } from "@nestjs/common";
import { Processor, WorkerHost } from "@nestjs/bullmq";
import type { Job } from "bullmq";
import { PrismaService } from "../common/prisma/prisma.service";
import { WebhooksService } from "../common/webhooks/webhooks.service";
import { STOCK_ALERTS_QUEUE } from "../common/queue/queue.module";

export interface LowStockCheckJob {
  companyId: string;
  materialCatalogItemId: string;
}

/**
 * Runs after every stock movement that could push a material below its reorder
 * threshold. Sums quantity on hand across all of the company's warehouses and,
 * when a preferred supplier and reorder quantity are configured, drafts a
 * purchase order automatically so restocking doesn't wait on someone noticing
 * the alert. Left in "draft" (never auto-submitted to the supplier) and tagged
 * autoGenerated so the office reviews quantities/pricing before ordering.
 */
@Processor(STOCK_ALERTS_QUEUE)
export class LowStockProcessor extends WorkerHost {
  private readonly logger = new Logger(LowStockProcessor.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly webhooks: WebhooksService,
  ) {
    super();
  }

  async process(job: Job<LowStockCheckJob>): Promise<{ belowThreshold: boolean; quantityOnHand?: number; draftedPurchaseOrderId?: string }> {
    const { companyId, materialCatalogItemId } = job.data;

    const material = await this.prisma.materialCatalogItem.findUnique({
      where: { id: materialCatalogItemId },
    });
    if (!material || material.reorderThreshold === null) {
      return { belowThreshold: false };
    }

    const levels = await this.prisma.stockLevel.findMany({ where: { materialCatalogItemId } });
    const quantityOnHand = levels.reduce((sum, l) => sum + Number(l.quantityOnHand), 0);

    const belowThreshold = quantityOnHand < Number(material.reorderThreshold);
    if (!belowThreshold) {
      return { belowThreshold: false, quantityOnHand };
    }

    this.logger.warn(
      `Low stock: ${material.code} (${material.name}) at ${quantityOnHand}${material.unit}, below reorder threshold of ${material.reorderThreshold}${material.unit}`,
    );
    this.webhooks.trigger(companyId, "material.low_stock", {
      materialCatalogItemId,
      code: material.code,
      name: material.name,
      quantityOnHand,
      unit: material.unit,
      reorderThreshold: Number(material.reorderThreshold),
    });

    if (!material.preferredSupplierId || material.reorderQuantity === null) {
      return { belowThreshold: true, quantityOnHand };
    }

    const existingOpenLine = await this.prisma.purchaseOrderLine.findFirst({
      where: {
        materialCatalogItemId,
        purchaseOrder: { companyId, supplierId: material.preferredSupplierId, status: { in: ["draft", "ordered"] } },
      },
    });
    if (existingOpenLine) {
      // Already have a pending order covering this material — don't spam a new one on every subsequent dip.
      return { belowThreshold: true, quantityOnHand };
    }

    const po = await this.prisma.purchaseOrder.create({
      data: {
        companyId,
        supplierId: material.preferredSupplierId,
        status: "draft",
        autoGenerated: true,
        lines: {
          create: [
            {
              materialCatalogItemId,
              quantity: material.reorderQuantity,
              unitPrice: material.defaultUnitPrice,
            },
          ],
        },
      },
    });
    this.logger.log(`Auto-drafted purchase order ${po.id} for ${material.code} (qty ${material.reorderQuantity})`);

    return { belowThreshold: true, quantityOnHand, draftedPurchaseOrderId: po.id };
  }
}
