"use client";

import { useEffect, useState } from "react";
import { useTranslations } from "next-intl";
import { apiFetch } from "@/lib/api-client";
import { useMe } from "@/lib/use-me";
import { formatDate } from "@/lib/format-date";

interface Supplier {
  id: string;
  name: string;
}
interface Warehouse {
  id: string;
  name: string;
}
interface MaterialCatalogItem {
  id: string;
  code: string;
  name: string;
}
interface POLine {
  id: string;
  quantity: string;
  quantityReceived: string;
  unitPrice: string;
  materialCatalogItem: MaterialCatalogItem;
}
interface PurchaseOrder {
  id: string;
  status: "draft" | "ordered" | "received" | "partially_received";
  autoGenerated: boolean;
  acknowledgedAt: string | null;
  supplierEta: string | null;
  supplierNote: string | null;
  supplier: Supplier;
  lines: POLine[];
}
interface DraftLine {
  materialCatalogItemId: string;
  quantity: string;
  unitPrice: string;
}
interface ShipmentLineDraft {
  lineId: string;
  quantityReceived: string;
  quantityDamaged: string;
  shortfallType: "" | "short_ship" | "backorder";
}

export function PurchaseOrdersPanel() {
  const t = useTranslations("purchaseOrders");
  const tc = useTranslations("common");
  const { data: me } = useMe();

  const [orders, setOrders] = useState<PurchaseOrder[] | null>(null);
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [warehouses, setWarehouses] = useState<Warehouse[]>([]);
  const [materials, setMaterials] = useState<MaterialCatalogItem[]>([]);
  const [supplierId, setSupplierId] = useState("");
  const [expectedDate, setExpectedDate] = useState("");
  const [lines, setLines] = useState<DraftLine[]>([]);
  const [submitting, setSubmitting] = useState(false);

  const [receivingOrderId, setReceivingOrderId] = useState<string | null>(null);
  const [shipmentLines, setShipmentLines] = useState<ShipmentLineDraft[]>([]);
  const [shipmentWarehouseId, setShipmentWarehouseId] = useState("");
  const [shipmentBusy, setShipmentBusy] = useState(false);

  function load() {
    apiFetch<PurchaseOrder[]>("/materials/purchase-orders").then(setOrders);
  }

  useEffect(() => {
    load();
    apiFetch<Supplier[]>("/materials/suppliers").then((s) => {
      setSuppliers(s);
      if (s[0]) setSupplierId(s[0].id);
    });
    apiFetch<Warehouse[]>("/materials/warehouses").then(setWarehouses);
    apiFetch<MaterialCatalogItem[]>("/materials/catalog").then(setMaterials);
  }, []);

  function addLine() {
    if (materials.length === 0) return;
    setLines((l) => [...l, { materialCatalogItemId: materials[0].id, quantity: "1", unitPrice: "0" }]);
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!supplierId || lines.length === 0) return;
    setSubmitting(true);
    try {
      await apiFetch("/materials/purchase-orders", {
        method: "POST",
        body: JSON.stringify({
          supplierId,
          expectedDate: expectedDate ? new Date(expectedDate).toISOString() : undefined,
          lines: lines.map((l) => ({
            materialCatalogItemId: l.materialCatalogItemId,
            quantity: Number(l.quantity),
            unitPrice: Number(l.unitPrice),
          })),
        }),
      });
      setLines([]);
      setExpectedDate("");
      load();
    } finally {
      setSubmitting(false);
    }
  }

  async function receive(orderId: string) {
    if (!warehouses[0]) return;
    await apiFetch(`/materials/purchase-orders/${orderId}/receive`, {
      method: "POST",
      body: JSON.stringify({ warehouseId: warehouses[0].id }),
    });
    load();
  }

  function openReceiveShipment(po: PurchaseOrder) {
    setReceivingOrderId(po.id);
    setShipmentWarehouseId(warehouses[0]?.id ?? "");
    setShipmentLines(
      po.lines
        .filter((l) => Number(l.quantityReceived) < Number(l.quantity))
        .map((l) => ({ lineId: l.id, quantityReceived: "", quantityDamaged: "", shortfallType: "" })),
    );
  }

  async function submitShipment() {
    if (!shipmentWarehouseId) return;
    const shipLines = shipmentLines
      .filter((l) => Number(l.quantityReceived) > 0)
      .map((l) => ({
        lineId: l.lineId,
        quantityReceived: Number(l.quantityReceived),
        quantityDamaged: l.quantityDamaged ? Number(l.quantityDamaged) : undefined,
        shortfallType: l.shortfallType || undefined,
      }));
    if (shipLines.length === 0 || !receivingOrderId) return;
    setShipmentBusy(true);
    try {
      await apiFetch(`/materials/purchase-orders/${receivingOrderId}/receive-shipment`, {
        method: "POST",
        body: JSON.stringify({ warehouseId: shipmentWarehouseId, lines: shipLines }),
      });
      setReceivingOrderId(null);
      setShipmentLines([]);
      load();
    } finally {
      setShipmentBusy(false);
    }
  }

  return (
    <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
      <div className="card lg:col-span-1">
        <h2 className="mb-4 text-sm font-semibold text-gray-700">{t("newOrder")}</h2>
        <form onSubmit={handleSubmit} className="flex flex-col gap-3">
          <select className="input" value={supplierId} onChange={(e) => setSupplierId(e.target.value)}>
            {suppliers.map((s) => (
              <option key={s.id} value={s.id}>
                {s.name}
              </option>
            ))}
          </select>
          <label className="text-xs text-gray-500">
            {t("expectedDate")}
            <input
              type="date"
              className="input mt-1"
              value={expectedDate}
              onChange={(e) => setExpectedDate(e.target.value)}
            />
          </label>

          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-gray-500">{t("material")}</span>
            <button type="button" onClick={addLine} className="btn-secondary px-2 py-1 text-xs">
              + {t("addLine")}
            </button>
          </div>
          {lines.map((line, i) => (
            <div key={i} className="flex gap-2">
              <select
                className="input"
                value={line.materialCatalogItemId}
                onChange={(e) =>
                  setLines((ls) => ls.map((l, j) => (j === i ? { ...l, materialCatalogItemId: e.target.value } : l)))
                }
              >
                {materials.map((m) => (
                  <option key={m.id} value={m.id}>
                    {m.code}
                  </option>
                ))}
              </select>
              <input
                type="number"
                step="0.01"
                min="0.01"
                placeholder={t("quantity")}
                className="input w-20"
                value={line.quantity}
                onChange={(e) => setLines((ls) => ls.map((l, j) => (j === i ? { ...l, quantity: e.target.value } : l)))}
              />
              <input
                type="number"
                step="0.01"
                min="0"
                placeholder={t("unitPrice")}
                className="input w-20"
                value={line.unitPrice}
                onChange={(e) =>
                  setLines((ls) => ls.map((l, j) => (j === i ? { ...l, unitPrice: e.target.value } : l)))
                }
              />
            </div>
          ))}

          <button type="submit" disabled={submitting || lines.length === 0} className="btn-primary mt-2">
            {tc("create")}
          </button>
        </form>
      </div>

      <div className="lg:col-span-2">
        {!orders ? (
          <p className="text-gray-500">{tc("loading")}</p>
        ) : (
          <ul className="flex flex-col gap-2">
            {orders.map((po) => (
              <li key={po.id} className="card">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 font-medium">
                    {po.supplier.name}
                    {po.autoGenerated && (
                      <span className="rounded-full bg-warning-50 px-2 py-0.5 text-xs font-medium text-warning-700">
                        {t("autoGenerated")}
                      </span>
                    )}
                  </div>
                  <span
                    className={`rounded-full px-2 py-0.5 text-xs ${
                      po.status === "received"
                        ? "bg-green-100 text-green-800"
                        : po.status === "partially_received"
                          ? "bg-warning-50 text-warning-700"
                          : "bg-gray-100 text-gray-600"
                    }`}
                  >
                    {t(po.status)}
                  </span>
                </div>
                <ul className="mt-2 text-sm text-gray-500">
                  {po.lines.map((l) => (
                    <li key={l.id}>
                      {l.materialCatalogItem.code} × {l.quantity} @ {l.unitPrice} {me?.company.currency}
                      {Number(l.quantityReceived) > 0 && (
                        <span className="ml-1.5 text-xs text-gray-400">({t("receivedOf", { received: l.quantityReceived, quantity: l.quantity })})</span>
                      )}
                    </li>
                  ))}
                </ul>
                {po.acknowledgedAt ? (
                  <p className="mt-2 text-xs text-success-700">
                    {t("acknowledgedBy", {
                      date: formatDate(new Date(po.acknowledgedAt)),
                      eta: po.supplierEta ? formatDate(new Date(po.supplierEta)) : "—",
                    })}
                    {po.supplierNote && <span className="block text-gray-500">{po.supplierNote}</span>}
                  </p>
                ) : (
                  po.status !== "draft" && <p className="mt-2 text-xs text-gray-400">{t("notAcknowledged")}</p>
                )}
                {po.status !== "received" && (
                  <div className="mt-3 flex gap-2">
                    <button onClick={() => receive(po.id)} className="btn-secondary">
                      {t("receive")}
                    </button>
                    <button onClick={() => openReceiveShipment(po)} className="btn-secondary">
                      {t("receiveShipment")}
                    </button>
                  </div>
                )}

                {receivingOrderId === po.id && (
                  <div className="mt-3 flex flex-col gap-2 border-t border-gray-100 pt-3">
                    <select className="input" value={shipmentWarehouseId} onChange={(e) => setShipmentWarehouseId(e.target.value)}>
                      {warehouses.map((w) => (
                        <option key={w.id} value={w.id}>
                          {w.name}
                        </option>
                      ))}
                    </select>
                    {shipmentLines.map((sl, i) => {
                      const line = po.lines.find((l) => l.id === sl.lineId)!;
                      return (
                        <div key={sl.lineId} className="flex flex-wrap items-center gap-2">
                          <span className="w-32 truncate text-xs text-gray-500">{line.materialCatalogItem.code}</span>
                          <input
                            type="number"
                            step="0.01"
                            min="0"
                            placeholder={t("quantityReceivedPlaceholder")}
                            className="input w-32"
                            value={sl.quantityReceived}
                            onChange={(e) => setShipmentLines((ls) => ls.map((l, j) => (j === i ? { ...l, quantityReceived: e.target.value } : l)))}
                          />
                          <input
                            type="number"
                            step="0.01"
                            min="0"
                            placeholder={t("quantityDamagedPlaceholder")}
                            className="input w-32"
                            value={sl.quantityDamaged}
                            onChange={(e) => setShipmentLines((ls) => ls.map((l, j) => (j === i ? { ...l, quantityDamaged: e.target.value } : l)))}
                          />
                          <select
                            className="input"
                            value={sl.shortfallType}
                            onChange={(e) => setShipmentLines((ls) => ls.map((l, j) => (j === i ? { ...l, shortfallType: e.target.value as ShipmentLineDraft["shortfallType"] } : l)))}
                          >
                            <option value="">{t("shortfallTypeNone")}</option>
                            <option value="short_ship">{t("shortfallType_short_ship")}</option>
                            <option value="backorder">{t("shortfallType_backorder")}</option>
                          </select>
                        </div>
                      );
                    })}
                    <div className="flex gap-2">
                      <button onClick={submitShipment} disabled={shipmentBusy} className="btn-primary px-3 py-1.5 text-xs">
                        {tc("save")}
                      </button>
                      <button onClick={() => setReceivingOrderId(null)} className="btn-secondary px-3 py-1.5 text-xs">
                        {tc("cancel")}
                      </button>
                    </div>
                  </div>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
