"use client";

import { useEffect, useState } from "react";
import { useTranslations } from "next-intl";
import { RECEIVING_DISCREPANCY_RESOLUTIONS, type ReceivingDiscrepancyResolution, type ReceivingDiscrepancyType } from "@cantero/shared";
import { AuthenticatedShell } from "@/components/authenticated-shell";
import { apiFetch } from "@/lib/api-client";
import { useMe } from "@/lib/use-me";
import { formatDate } from "@/lib/format-date";

interface Supplier {
  id: string;
  name: string;
}
interface Warehouse {
  id: string;
  name: string;
}
interface MaterialCatalogItem {
  id: string;
  code: string;
  name: string;
}
interface POLine {
  id: string;
  quantity: string;
  quantityReceived: string;
  unitPrice: string;
  materialCatalogItem: MaterialCatalogItem;
}
interface PurchaseOrder {
  id: string;
  status: "draft" | "ordered" | "received" | "partially_received";
  autoGenerated: boolean;
  acknowledgedAt: string | null;
  supplierEta: string | null;
  supplierNote: string | null;
  supplier: Supplier;
  lines: POLine[];
}

interface DraftLine {
  materialCatalogItemId: string;
  quantity: string;
  unitPrice: string;
}

interface ReceivingDiscrepancy {
  id: string;
  type: ReceivingDiscrepancyType;
  quantity: string;
  resolution: ReceivingDiscrepancyResolution;
  resolutionNotes: string | null;
  purchaseOrder: { id: string; supplier: { id: string; name: string } };
  purchaseOrderLine: { id: string; materialCatalogItem: { id: string; code: string; name: string } };
}
interface ShipmentLineDraft {
  lineId: string;
  quantityReceived: string;
  quantityDamaged: string;
  shortfallType: "" | "short_ship" | "backorder";
}

interface VendorBillLine {
  id: string;
  description: string;
  quantity: string;
  unitPrice: string;
  materialCatalogItem: MaterialCatalogItem | null;
}
interface MatchLineResult {
  materialCatalogItemId: string;
  orderedQuantity: number;
  orderedUnitPrice: number;
  billedQuantity: number;
  billedUnitPrice: number;
  quantityVariance: number;
  priceVariance: number;
}
interface VendorBillMatch {
  status: "no_po" | "matched" | "variance";
  lines: MatchLineResult[];
}
interface VendorBill {
  id: string;
  billNumber: string;
  billDate: string;
  dueDate: string | null;
  scheduledPaymentDate: string | null;
  status: "draft" | "approved" | "paid";
  supplier: Supplier;
  purchaseOrder: { id: string } | null;
  lines: VendorBillLine[];
  match: VendorBillMatch;
}
interface DisbursementBucket {
  weekStart: string;
  weekEnd: string;
  total: number;
  bills: { id: string; billNumber: string; supplierName: string; amount: number }[];
}
interface DisbursementCalendar {
  buckets: DisbursementBucket[];
  unscheduledTotal: number;
  unscheduledBills: { id: string; billNumber: string; supplierName: string; amount: number }[];
}
interface DraftBillLine {
  description: string;
  quantity: string;
  unitPrice: string;
}
interface ApAgingBill {
  id: string;
  billNumber: string;
  supplierName: string;
  amount: number;
  daysPastDue: number;
  bucket: "current" | "days1to30" | "days31to60" | "days61to90" | "over90";
}
interface ApAgingReport {
  bills: ApAgingBill[];
  totalsByBucket: Record<string, number>;
  grandTotal: number;
}

export default function PurchaseOrdersPage() {
  const t = useTranslations("purchaseOrders");
  const tc = useTranslations("common");
  const { data: me } = useMe();

  const [orders, setOrders] = useState<PurchaseOrder[] | null>(null);
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [warehouses, setWarehouses] = useState<Warehouse[]>([]);
  const [materials, setMaterials] = useState<MaterialCatalogItem[]>([]);
  const [supplierId, setSupplierId] = useState("");
  const [expectedDate, setExpectedDate] = useState("");
  const [lines, setLines] = useState<DraftLine[]>([]);
  const [submitting, setSubmitting] = useState(false);

  const [bills, setBills] = useState<VendorBill[] | null>(null);
  const [aging, setAging] = useState<ApAgingReport | null>(null);
  const [disbursementCalendar, setDisbursementCalendar] = useState<DisbursementCalendar | null>(null);
  const [scheduleDrafts, setScheduleDrafts] = useState<Record<string, string>>({});
  const [discrepancies, setDiscrepancies] = useState<ReceivingDiscrepancy[] | null>(null);
  const [receivingOrderId, setReceivingOrderId] = useState<string | null>(null);
  const [shipmentLines, setShipmentLines] = useState<ShipmentLineDraft[]>([]);
  const [shipmentWarehouseId, setShipmentWarehouseId] = useState("");
  const [shipmentBusy, setShipmentBusy] = useState(false);
  const [resolvingId, setResolvingId] = useState<string | null>(null);
  const [resolutionForm, setResolutionForm] = useState({ resolution: "credit_issued" as ReceivingDiscrepancyResolution, resolutionNotes: "" });
  const [addingBill, setAddingBill] = useState(false);
  const [billSupplierId, setBillSupplierId] = useState("");
  const [billPurchaseOrderId, setBillPurchaseOrderId] = useState("");
  const [billNumber, setBillNumber] = useState("");
  const [billDueDate, setBillDueDate] = useState("");
  const [billLines, setBillLines] = useState<DraftBillLine[]>([]);
  const [billSubmitting, setBillSubmitting] = useState(false);

  function load() {
    apiFetch<PurchaseOrder[]>("/materials/purchase-orders").then(setOrders);
  }

  function loadDiscrepancies() {
    apiFetch<ReceivingDiscrepancy[]>("/materials/purchase-orders/receiving-discrepancies").then(setDiscrepancies);
  }

  function loadBills() {
    apiFetch<VendorBill[]>("/materials/vendor-bills").then(setBills);
    apiFetch<ApAgingReport>("/materials/vendor-bills/aging-report").then(setAging);
    apiFetch<DisbursementCalendar>("/materials/vendor-bills/disbursement-calendar").then(setDisbursementCalendar);
  }

  useEffect(() => {
    load();
    loadBills();
    loadDiscrepancies();
    apiFetch<Supplier[]>("/materials/suppliers").then((s) => {
      setSuppliers(s);
      if (s[0]) {
        setSupplierId(s[0].id);
        setBillSupplierId(s[0].id);
      }
    });
    apiFetch<Warehouse[]>("/materials/warehouses").then(setWarehouses);
    apiFetch<MaterialCatalogItem[]>("/materials/catalog").then(setMaterials);
  }, []);

  function addBillLine() {
    setBillLines((l) => [...l, { description: "", quantity: "1", unitPrice: "0" }]);
  }

  async function submitBill(e: React.FormEvent) {
    e.preventDefault();
    if (!billSupplierId || !billNumber.trim() || billLines.length === 0) return;
    setBillSubmitting(true);
    try {
      await apiFetch("/materials/vendor-bills", {
        method: "POST",
        body: JSON.stringify({
          supplierId: billSupplierId,
          purchaseOrderId: billPurchaseOrderId || undefined,
          billNumber: billNumber.trim(),
          dueDate: billDueDate ? new Date(billDueDate).toISOString() : undefined,
          lines: billLines.map((l) => ({ description: l.description, quantity: Number(l.quantity), unitPrice: Number(l.unitPrice) })),
        }),
      });
      setBillNumber("");
      setBillDueDate("");
      setBillPurchaseOrderId("");
      setBillLines([]);
      setAddingBill(false);
      loadBills();
    } finally {
      setBillSubmitting(false);
    }
  }

  async function approveBill(billId: string) {
    await apiFetch(`/materials/vendor-bills/${billId}/approve`, { method: "POST" });
    loadBills();
  }

  async function payBill(billId: string) {
    await apiFetch(`/materials/vendor-bills/${billId}/pay`, { method: "POST" });
    loadBills();
  }

  async function schedulePayment(billId: string) {
    const date = scheduleDrafts[billId];
    if (!date) return;
    await apiFetch(`/materials/vendor-bills/${billId}/schedule-payment`, {
      method: "POST",
      body: JSON.stringify({ scheduledPaymentDate: new Date(date).toISOString() }),
    });
    setScheduleDrafts((f) => ({ ...f, [billId]: "" }));
    loadBills();
  }

  function addLine() {
    if (materials.length === 0) return;
    setLines((l) => [...l, { materialCatalogItemId: materials[0].id, quantity: "1", unitPrice: "0" }]);
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!supplierId || lines.length === 0) return;
    setSubmitting(true);
    try {
      await apiFetch("/materials/purchase-orders", {
        method: "POST",
        body: JSON.stringify({
          supplierId,
          expectedDate: expectedDate ? new Date(expectedDate).toISOString() : undefined,
          lines: lines.map((l) => ({
            materialCatalogItemId: l.materialCatalogItemId,
            quantity: Number(l.quantity),
            unitPrice: Number(l.unitPrice),
          })),
        }),
      });
      setLines([]);
      setExpectedDate("");
      load();
    } finally {
      setSubmitting(false);
    }
  }

  async function receive(orderId: string) {
    if (!warehouses[0]) return;
    await apiFetch(`/materials/purchase-orders/${orderId}/receive`, {
      method: "POST",
      body: JSON.stringify({ warehouseId: warehouses[0].id }),
    });
    load();
  }

  function openReceiveShipment(po: PurchaseOrder) {
    setReceivingOrderId(po.id);
    setShipmentWarehouseId(warehouses[0]?.id ?? "");
    setShipmentLines(
      po.lines
        .filter((l) => Number(l.quantityReceived) < Number(l.quantity))
        .map((l) => ({ lineId: l.id, quantityReceived: "", quantityDamaged: "", shortfallType: "" })),
    );
  }

  async function submitShipment() {
    if (!shipmentWarehouseId) return;
    const lines = shipmentLines
      .filter((l) => Number(l.quantityReceived) > 0)
      .map((l) => ({
        lineId: l.lineId,
        quantityReceived: Number(l.quantityReceived),
        quantityDamaged: l.quantityDamaged ? Number(l.quantityDamaged) : undefined,
        shortfallType: l.shortfallType || undefined,
      }));
    if (lines.length === 0 || !receivingOrderId) return;
    setShipmentBusy(true);
    try {
      await apiFetch(`/materials/purchase-orders/${receivingOrderId}/receive-shipment`, {
        method: "POST",
        body: JSON.stringify({ warehouseId: shipmentWarehouseId, lines }),
      });
      setReceivingOrderId(null);
      setShipmentLines([]);
      load();
      loadDiscrepancies();
    } finally {
      setShipmentBusy(false);
    }
  }

  async function resolveDiscrepancy(id: string) {
    await apiFetch(`/materials/purchase-orders/receiving-discrepancies/${id}/resolve`, {
      method: "POST",
      body: JSON.stringify({ resolution: resolutionForm.resolution, resolutionNotes: resolutionForm.resolutionNotes || undefined }),
    });
    setResolvingId(null);
    setResolutionForm({ resolution: "credit_issued", resolutionNotes: "" });
    loadDiscrepancies();
  }

  return (
    <AuthenticatedShell>
      <h1 className="text-2xl font-semibold">{t("title")}</h1>

      <div className="mt-6 grid grid-cols-1 gap-8 lg:grid-cols-3">
        <div className="card lg:col-span-1">
          <h2 className="mb-4 text-sm font-semibold text-gray-700">{t("newOrder")}</h2>
          <form onSubmit={handleSubmit} className="flex flex-col gap-3">
            <select className="input" value={supplierId} onChange={(e) => setSupplierId(e.target.value)}>
              {suppliers.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
            <label className="text-xs text-gray-500">
              {t("expectedDate")}
              <input
                type="date"
                className="input mt-1"
                value={expectedDate}
                onChange={(e) => setExpectedDate(e.target.value)}
              />
            </label>

            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-gray-500">{t("material")}</span>
              <button type="button" onClick={addLine} className="btn-secondary px-2 py-1 text-xs">
                + {t("addLine")}
              </button>
            </div>
            {lines.map((line, i) => (
              <div key={i} className="flex gap-2">
                <select
                  className="input"
                  value={line.materialCatalogItemId}
                  onChange={(e) =>
                    setLines((ls) => ls.map((l, j) => (j === i ? { ...l, materialCatalogItemId: e.target.value } : l)))
                  }
                >
                  {materials.map((m) => (
                    <option key={m.id} value={m.id}>
                      {m.code}
                    </option>
                  ))}
                </select>
                <input
                  type="number"
                  step="0.01"
                  placeholder={t("quantity")}
                  className="input w-20"
                  value={line.quantity}
                  onChange={(e) => setLines((ls) => ls.map((l, j) => (j === i ? { ...l, quantity: e.target.value } : l)))}
                />
                <input
                  type="number"
                  step="0.01"
                  placeholder={t("unitPrice")}
                  className="input w-20"
                  value={line.unitPrice}
                  onChange={(e) =>
                    setLines((ls) => ls.map((l, j) => (j === i ? { ...l, unitPrice: e.target.value } : l)))
                  }
                />
              </div>
            ))}

            <button type="submit" disabled={submitting || lines.length === 0} className="btn-primary mt-2">
              {tc("create")}
            </button>
          </form>
        </div>

        <div className="lg:col-span-2">
          {!orders ? (
            <p className="text-gray-500">{tc("loading")}</p>
          ) : (
            <ul className="flex flex-col gap-2">
              {orders.map((po) => (
                <li key={po.id} className="card">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2 font-medium">
                      {po.supplier.name}
                      {po.autoGenerated && (
                        <span className="rounded-full bg-warning-50 px-2 py-0.5 text-xs font-medium text-warning-700">
                          {t("autoGenerated")}
                        </span>
                      )}
                    </div>
                    <span
                      className={`rounded-full px-2 py-0.5 text-xs ${
                        po.status === "received"
                          ? "bg-green-100 text-green-800"
                          : po.status === "partially_received"
                            ? "bg-warning-50 text-warning-700"
                            : "bg-gray-100 text-gray-600"
                      }`}
                    >
                      {t(po.status)}
                    </span>
                  </div>
                  <ul className="mt-2 text-sm text-gray-500">
                    {po.lines.map((l) => (
                      <li key={l.id}>
                        {l.materialCatalogItem.code} × {l.quantity} @ {l.unitPrice} {me?.company.currency}
                        {Number(l.quantityReceived) > 0 && (
                          <span className="ml-1.5 text-xs text-gray-400">({t("receivedOf", { received: l.quantityReceived, quantity: l.quantity })})</span>
                        )}
                      </li>
                    ))}
                  </ul>
                  {po.acknowledgedAt ? (
                    <p className="mt-2 text-xs text-success-700">
                      {t("acknowledgedBy", {
                        date: formatDate(new Date(po.acknowledgedAt)),
                        eta: po.supplierEta ? formatDate(new Date(po.supplierEta)) : "—",
                      })}
                      {po.supplierNote && <span className="block text-gray-500">{po.supplierNote}</span>}
                    </p>
                  ) : (
                    po.status !== "draft" && <p className="mt-2 text-xs text-gray-400">{t("notAcknowledged")}</p>
                  )}
                  {po.status !== "received" && (
                    <div className="mt-3 flex gap-2">
                      <button onClick={() => receive(po.id)} className="btn-secondary">
                        {t("receive")}
                      </button>
                      <button onClick={() => openReceiveShipment(po)} className="btn-secondary">
                        {t("receiveShipment")}
                      </button>
                    </div>
                  )}

                  {receivingOrderId === po.id && (
                    <div className="mt-3 flex flex-col gap-2 border-t border-gray-100 pt-3">
                      <select className="input" value={shipmentWarehouseId} onChange={(e) => setShipmentWarehouseId(e.target.value)}>
                        {warehouses.map((w) => (
                          <option key={w.id} value={w.id}>
                            {w.name}
                          </option>
                        ))}
                      </select>
                      {shipmentLines.map((sl, i) => {
                        const line = po.lines.find((l) => l.id === sl.lineId)!;
                        return (
                          <div key={sl.lineId} className="flex flex-wrap items-center gap-2">
                            <span className="w-32 truncate text-xs text-gray-500">{line.materialCatalogItem.code}</span>
                            <input
                              type="number"
                              step="0.01"
                              min="0"
                              placeholder={t("quantityReceivedPlaceholder")}
                              className="input w-32"
                              value={sl.quantityReceived}
                              onChange={(e) => setShipmentLines((ls) => ls.map((l, j) => (j === i ? { ...l, quantityReceived: e.target.value } : l)))}
                            />
                            <input
                              type="number"
                              step="0.01"
                              min="0"
                              placeholder={t("quantityDamagedPlaceholder")}
                              className="input w-32"
                              value={sl.quantityDamaged}
                              onChange={(e) => setShipmentLines((ls) => ls.map((l, j) => (j === i ? { ...l, quantityDamaged: e.target.value } : l)))}
                            />
                            <select
                              className="input"
                              value={sl.shortfallType}
                              onChange={(e) => setShipmentLines((ls) => ls.map((l, j) => (j === i ? { ...l, shortfallType: e.target.value as ShipmentLineDraft["shortfallType"] } : l)))}
                            >
                              <option value="">{t("shortfallTypeNone")}</option>
                              <option value="short_ship">{t("shortfallType_short_ship")}</option>
                              <option value="backorder">{t("shortfallType_backorder")}</option>
                            </select>
                          </div>
                        );
                      })}
                      <div className="flex gap-2">
                        <button onClick={submitShipment} disabled={shipmentBusy} className="btn-primary px-3 py-1.5 text-xs">
                          {tc("save")}
                        </button>
                        <button onClick={() => setReceivingOrderId(null)} className="btn-secondary px-3 py-1.5 text-xs">
                          {tc("cancel")}
                        </button>
                      </div>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>

      <div className="mt-10">
        <h2 className="mb-1 text-sm font-semibold text-gray-700">{t("discrepanciesTitle")}</h2>
        <p className="mb-3 text-xs text-gray-500">{t("discrepanciesHint")}</p>
        {!discrepancies ? (
          <p className="text-sm text-gray-500">{tc("loading")}</p>
        ) : discrepancies.length === 0 ? (
          <p className="text-sm text-gray-400">{t("noDiscrepancies")}</p>
        ) : (
          <ul className="flex flex-col gap-2">
            {discrepancies.map((d) => (
              <li key={d.id} className="card">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-gray-900">
                    {t(`discrepancyType_${d.type}`)} · {d.purchaseOrderLine.materialCatalogItem.code} × {d.quantity}
                  </span>
                  <span
                    className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                      d.resolution === "pending" ? "bg-warning-50 text-warning-700" : "bg-success-50 text-success-700"
                    }`}
                  >
                    {t(`resolution_${d.resolution}`)}
                  </span>
                </div>
                <p className="mt-1 text-xs text-gray-400">{d.purchaseOrder.supplier.name}</p>
                {d.resolutionNotes && <p className="mt-1 text-xs text-gray-500">{d.resolutionNotes}</p>}
                {d.resolution === "pending" &&
                  (resolvingId === d.id ? (
                    <div className="mt-2 flex flex-wrap items-center gap-2">
                      <select
                        className="input"
                        value={resolutionForm.resolution}
                        onChange={(e) => setResolutionForm((f) => ({ ...f, resolution: e.target.value as ReceivingDiscrepancyResolution }))}
                      >
                        {RECEIVING_DISCREPANCY_RESOLUTIONS.filter((r) => r !== "pending").map((r) => (
                          <option key={r} value={r}>
                            {t(`resolution_${r}`)}
                          </option>
                        ))}
                      </select>
                      <input
                        placeholder={t("resolutionNotesPlaceholder")}
                        className="input flex-1"
                        value={resolutionForm.resolutionNotes}
                        onChange={(e) => setResolutionForm((f) => ({ ...f, resolutionNotes: e.target.value }))}
                      />
                      <button onClick={() => resolveDiscrepancy(d.id)} className="btn-primary px-2.5 py-1 text-xs">
                        {tc("save")}
                      </button>
                      <button onClick={() => setResolvingId(null)} className="btn-secondary px-2.5 py-1 text-xs">
                        {tc("cancel")}
                      </button>
                    </div>
                  ) : (
                    <button onClick={() => setResolvingId(d.id)} className="btn-secondary mt-2 px-2.5 py-1 text-xs">
                      {t("resolve")}
                    </button>
                  ))}
              </li>
            ))}
          </ul>
        )}
      </div>

      <div className="mt-10">
        <h2 className="mb-1 text-sm font-semibold text-gray-700">{t("vendorBillsTitle")}</h2>
        <p className="mb-3 text-xs text-gray-500">{t("vendorBillsHint")}</p>

        {aging && aging.grandTotal > 0 && (
          <div className="card mb-4">
            <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-500">{t("apAgingTitle")}</h3>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">
              {(["current", "days1to30", "days31to60", "days61to90", "over90"] as const).map((bucket) => (
                <div key={bucket}>
                  <div className="text-xs text-gray-500">{t(`agingBucket_${bucket}`)}</div>
                  <div className="mt-1 text-sm font-semibold text-gray-900">
                    {aging.totalsByBucket[bucket] ?? 0} {me?.company.currency}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
          <div className="card lg:col-span-1">
            <div className="mb-4 flex items-center justify-between">
              <h3 className="text-sm font-semibold text-gray-700">{t("newVendorBill")}</h3>
              {!addingBill && (
                <button onClick={() => setAddingBill(true)} className="btn-secondary px-2.5 py-1 text-xs">
                  {tc("create")}
                </button>
              )}
            </div>
            {addingBill && (
              <form onSubmit={submitBill} className="flex flex-col gap-3">
                <select className="input" value={billSupplierId} onChange={(e) => setBillSupplierId(e.target.value)}>
                  {suppliers.map((s) => (
                    <option key={s.id} value={s.id}>
                      {s.name}
                    </option>
                  ))}
                </select>
                <select className="input" value={billPurchaseOrderId} onChange={(e) => setBillPurchaseOrderId(e.target.value)}>
                  <option value="">{t("noLinkedPurchaseOrder")}</option>
                  {(orders ?? [])
                    .filter((po) => po.supplier.id === billSupplierId)
                    .map((po) => (
                      <option key={po.id} value={po.id}>
                        {po.id.slice(0, 8)} — {t(po.status)}
                      </option>
                    ))}
                </select>
                <input
                  required
                  placeholder={t("billNumberPlaceholder")}
                  className="input"
                  value={billNumber}
                  onChange={(e) => setBillNumber(e.target.value)}
                />
                <label className="text-xs text-gray-500">
                  {t("dueDate")}
                  <input type="date" className="input mt-1" value={billDueDate} onChange={(e) => setBillDueDate(e.target.value)} />
                </label>

                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-gray-500">{t("billLines")}</span>
                  <button type="button" onClick={addBillLine} className="btn-secondary px-2 py-1 text-xs">
                    + {t("addLine")}
                  </button>
                </div>
                {billLines.map((line, i) => (
                  <div key={i} className="flex gap-2">
                    <input
                      required
                      placeholder={t("lineDescriptionPlaceholder")}
                      className="input"
                      value={line.description}
                      onChange={(e) => setBillLines((ls) => ls.map((l, j) => (j === i ? { ...l, description: e.target.value } : l)))}
                    />
                    <input
                      type="number"
                      step="0.01"
                      placeholder={t("quantity")}
                      className="input w-20"
                      value={line.quantity}
                      onChange={(e) => setBillLines((ls) => ls.map((l, j) => (j === i ? { ...l, quantity: e.target.value } : l)))}
                    />
                    <input
                      type="number"
                      step="0.01"
                      placeholder={t("unitPrice")}
                      className="input w-20"
                      value={line.unitPrice}
                      onChange={(e) => setBillLines((ls) => ls.map((l, j) => (j === i ? { ...l, unitPrice: e.target.value } : l)))}
                    />
                  </div>
                ))}

                <div className="flex gap-2">
                  <button type="submit" disabled={billSubmitting || billLines.length === 0} className="btn-primary">
                    {tc("create")}
                  </button>
                  <button type="button" onClick={() => setAddingBill(false)} className="btn-secondary">
                    {tc("cancel")}
                  </button>
                </div>
              </form>
            )}
          </div>

          <div className="lg:col-span-2">
            {!bills ? (
              <p className="text-gray-500">{tc("loading")}</p>
            ) : bills.length === 0 ? (
              <p className="text-gray-500">{t("noVendorBills")}</p>
            ) : (
              <ul className="flex flex-col gap-2">
                {bills.map((bill) => (
                  <li key={bill.id} className="card">
                    <div className="flex items-center justify-between">
                      <div className="font-medium">
                        {bill.billNumber} · {bill.supplier.name}
                      </div>
                      <div className="flex items-center gap-2">
                        {bill.match.status !== "no_po" && (
                          <span
                            className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                              bill.match.status === "variance" ? "bg-error-50 text-error-700" : "bg-success-50 text-success-700"
                            }`}
                          >
                            {t(`matchStatus_${bill.match.status}`)}
                          </span>
                        )}
                        <span
                          className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                            bill.status === "paid"
                              ? "bg-success-50 text-success-700"
                              : bill.status === "approved"
                                ? "bg-brand-50 text-brand-700"
                                : "bg-gray-100 text-gray-600"
                          }`}
                        >
                          {t(`billStatus_${bill.status}`)}
                        </span>
                      </div>
                    </div>
                    <ul className="mt-2 text-sm text-gray-500">
                      {bill.lines.map((l) => (
                        <li key={l.id}>
                          {l.description} × {l.quantity} @ {l.unitPrice} {me?.company.currency}
                        </li>
                      ))}
                    </ul>
                    {bill.dueDate && <p className="mt-1 text-xs text-gray-400">{t("dueDate")}: {formatDate(new Date(bill.dueDate))}</p>}
                    {bill.scheduledPaymentDate && (
                      <p className="mt-1 text-xs text-gray-400">{t("scheduledPaymentDate")}: {formatDate(new Date(bill.scheduledPaymentDate))}</p>
                    )}
                    <div className="mt-3 flex flex-wrap items-center gap-2">
                      {bill.status === "draft" && (
                        <button onClick={() => approveBill(bill.id)} className="btn-secondary px-2 py-1 text-xs">
                          {t("approveBill")}
                        </button>
                      )}
                      {bill.status === "approved" && (
                        <>
                          <button onClick={() => payBill(bill.id)} className="btn-secondary px-2 py-1 text-xs">
                            {t("markPaid")}
                          </button>
                          <input
                            type="date"
                            className="input py-1 text-xs"
                            value={scheduleDrafts[bill.id] ?? ""}
                            onChange={(e) => setScheduleDrafts((f) => ({ ...f, [bill.id]: e.target.value }))}
                          />
                          <button
                            onClick={() => schedulePayment(bill.id)}
                            disabled={!scheduleDrafts[bill.id]}
                            className="btn-secondary px-2 py-1 text-xs"
                          >
                            {t("schedulePayment")}
                          </button>
                        </>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </div>

          {disbursementCalendar && disbursementCalendar.buckets.some((b) => b.total > 0) && (
            <div className="card mt-4 lg:col-span-3">
              <h3 className="mb-1 text-sm font-semibold text-gray-700">{t("disbursementCalendar")}</h3>
              <p className="mb-3 text-xs text-gray-500">{t("disbursementCalendarHint")}</p>
              <div className="overflow-x-auto">
                <table className="w-full min-w-[480px] border-collapse text-sm">
                  <thead>
                    <tr className="border-b border-gray-200 text-left text-gray-500">
                      <th className="py-1">{t("weekOf")}</th>
                      <th className="text-right">{t("totalDue")}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {disbursementCalendar.buckets.map((b) => (
                      <tr key={b.weekStart} className="border-b border-gray-100">
                        <td className="py-1">{formatDate(new Date(b.weekStart))}</td>
                        <td className="text-right tabular-nums">
                          {b.total.toFixed(2)} {me?.company.currency}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {disbursementCalendar.unscheduledTotal > 0 && (
                <p className="mt-2 text-xs text-gray-500">
                  {t("unscheduledTotal", { amount: disbursementCalendar.unscheduledTotal.toFixed(2), currency: me?.company.currency ?? "" })}
                </p>
              )}
            </div>
          )}
        </div>
      </div>
    </AuthenticatedShell>
  );
}
