import { Controller, Get, Header, Param, StreamableFile } from "@nestjs/common";
import { Public } from "../common/decorators/public.decorator";
import { CompanyCoiService } from "./company-coi.service";

/** Unauthenticated — reached only via the token embedded in the link generated by
 * CompanyCoiService.setCoiPubliclyShared(), same pattern as PublicSubcontractorsController. */
@Controller("public/company-coi")
export class PublicCompanyCoiController {
  constructor(private readonly service: CompanyCoiService) {}

  @Public()
  @Get(":token")
  get(@Param("token") token: string) {
    return this.service.getPublicCoi(token);
  }

  @Public()
  @Get(":token/documents/:documentId/download")
  @Header("Content-Type", "application/octet-stream")
  async download(@Param("token") token: string, @Param("documentId") documentId: string) {
    const { buffer, name } = await this.service.downloadPublicDocument(token, documentId);
    return new StreamableFile(buffer, { disposition: `attachment; filename="${name}"` });
  }
}
